package com.fsd.utils;

public class SQL {
    public static final String LOGIN_SQL = "SELECT USERNAME, USERTYPE, ID FROM ECOMFSD.USER WHERE USERNAME = ? AND PASSWD = ?";
    public static final String REGISTER_SQL = "INSERT INTO ECOMFSD.USER (USERNAME, PASSWD, USERTYPE, CONTNUM, EMAIL, ADDRESS, DOJ) " +
            "VALUES (?, ?, ?, ?, ?, ?, SYSDATE());";
    public static String INSERT_PRODUCT = "INSERT INTO ECOMFSD.PRODUCT(NAME, MAKE_YEAR, CATEGORY, MODEL_NUMBER, PRICE, SELLER_ID, QUANTITY, SPECS, REMARKS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);";
    public static String UPDATE_PRODUCT_QUANTITY = "UPDATE ECOMFSD.PRODUCT SET QUANTITY = ?  WHERE ID = ?;";
    public static String UPDATE_PRODUCT_PRICE = "UPDATE ECOMFSD.PRODUCT SET PRICE = ?  WHERE ID = ?;";
    public static String GET_PRODUCT_DETAILS = "SELECT * FROM ECOMFSD.PRODUCT WHERE ID = ?;";
    public static String GET_PRODUCTS_FOR_SELLER_ID = "SELECT * FROM ECOMFSD.PRODUCT WHERE SELLER_ID = ?;";

    // Buyers Queries
    public static String GET_ALL_PRODUCT = "SELECT * FROM ECOMFSD.PRODUCT WHERE 1 = 1 ";
    public static String GET_PURCHASE_HISTORY = "SELECT * FROM ECOMFSD.PURCHASE_HISTORY WHERE BUYER_ID = ? ";
    public static String INSERT_PURCHASE_HISTORY = "INSERT INTO ECOMFSD.PURCHASE_HISTORY(PRODUCT_ID, PRICE, BUYER_ID, QUANTITY, ORDER_DATE_TIME) VALUES (?, ?, ?, ?, SYSDATE());";

}
