CREATE TABLE `ECOMFSD.PURCHASE_HISTORY` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` int(10) NOT NULL,
  `PRICE` DECIMAL(10,2) NOT NULL,
  `BUYER_ID` int(10) NOT NULL,
  `QUANTITY` int(4) NOT NULL,
  `ORDER_DATE_TIME` date NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (PRODUCT_ID) REFERENCES ECOMFSD.PRODUCT(ID),
  FOREIGN KEY (BUYER_ID) REFERENCES ECOMFSD.USER(ID)
) AUTO_INCREMENT=1000000001;